# Generated by Django 4.1.5 on 2023-01-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
