# Generated by Django 4.1.5 on 2023-01-13 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_userprofile_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionowed',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_owes_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='made_by',
            field=models.ForeignKey(db_column='payer', on_delete=django.db.models.deletion.CASCADE, related_name='made_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TransactionPaid',
        ),
    ]
